version: '3'
services:
  mock1:
    image: karate-mock-server:1.0.0
    ports:
      - "9000:9000"
    environment:
      PORT: "9000"
      SCRIPT: "mock-server.feature"
    volumes:
      - ./target:/target
      - ./:/karate